### ISSUE TITLE
deprecated on PHP 8.1.7: Headers::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists

### ISSUE THREAD

**Issue by rolandseuhs** [gggeek/phpxmlrpc#100]
Hi,

I get this message when running the latest release on PHP 8.1.7:

E_DEPRECATED (8192) "phar:///clx/ds/FALK/ext/php/httpful/httpful_2017-05-11.phar/Httpful/Response/Headers.php", 37
Return type of Httpful\Response\Headers::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by gggeek** [comment]
I think that this issue is coming from another library: nategood/httpful. It might even have already been reported as https://github.com/nategood/httpful/issues/296

**Comment by rolandseuhs** [comment]
Sorry, you are correct.

It looks as if httpful is not even maintained anymore...
