### ISSUE TITLE
Support <NIL/> extension - or at least don't crash

### ISSUE THREAD

**Issue by rolandseuhs** [gggeek/phpxmlrpc#102]
I have data that I have to process which contains:

```
<member>
<name>Meal</name>
<value>
	<nil/>
</value>
</member>
```

phpxmlrpc fails in src/Helper/XMLParser.php at:
```
// we do not support the <NIL/> extension, so  
// drop through intentionally

```
I just added this to the lines before:

```
						  $this->_xh['ac'] = ''; // reset the accumulator
						  break;

```

And now it seems to work fine (if I am not mistaken "`<nil/>`" is the same as an empty string, which is perfectly fine for my application).

I'm not sure how `<nil>` should be implemented (probably insert a real "null" value instead of an empty string), but I think treating it as an empty string is much better than just refusing to work).

In my case we have been using phpxmlrpc for 359 clients to transfer data for over 2 years. It has worked fine all this time, but about a week ago, the above `<nil/>` element has completely messed up the connection for one client.

So I would propose to use the above lines and just treat `<nil/>` as an empty string, it makes the implementation much more robust.

**Comment by gggeek** [comment]
Iirc nil/ is already supported. In order to enable that support, you have to set a flag value in the `\PhpXmlRpc` class - see https://github.com/gggeek/phpxmlrpc/blob/master/src/PhpXmlRpc.php#L90

**Comment by rolandseuhs** [comment]
Thanks a lot, I should have figured that out by looking at the code.

Is there any benefit of having $xmlrpc_null_extension set to false by default?

In any case the comment 

`// we do not support the <NIL/> extension, so`

should be changed to

`// the <NIL/> extension ($xmlrpc_null_extension) is turned off, so`

**Comment by gggeek** [comment]
Indeed, I will improve the comment in a future update :-)
Closing as already implemented.

**Comment by gggeek** [comment]
ps: rationale for `$xmlrpc_null_extension = false`

There are multiple extensions to the phpxmlrpc spec, some in more widespread use than others. The lib made the choice of not enabling any such extension by default, to avoid having to deal with choosing which ones to support and which ones not, which can be tricky, esp. in cases such as when there are slightly incompatible extensions floating around. The only exception to this policy iirc is the native support for introspection and multicall (the `system.` methods).

I do not see the need for the one-liner  `$xmlrpc_null_extension = true;` as a big inconvenience.
After all, the Client class has many more feature flags that one should take care of for optimizing calls in his/her context.
