### ISSUE TITLE
PHP 8.1 deprecated strftime and gmstrftime

### ISSUE THREAD

**Issue by stronk7** [gggeek/phpxmlrpc#103]
Reference: https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

>  The strftime() and gmstrftime() functions have been deprecated in favor of
    date()/DateTime::format() (for locale-independent formatting) or
    IntlDateFormatter::format() (for locale-dependent formatting).

There are a few uses in the library:

```
$  ag '[^:](gm)?strftime\('
debugger/action.php
274:            echo(strftime("%d/%b/%Y:%H:%M:%S\n"));
279:            echo(strftime("%d/%b/%Y:%H:%M:%S\n"));

src/Helper/Date.php
26:            $t = strftime("%Y%m%dT%H:%M:%S", $timet);
30:                $t = gmstrftime("%Y%m%dT%H:%M:%S", $timet);
32:                $t = strftime("%Y%m%dT%H:%M:%S", $timet - date('Z'));

src/Value.php
310:                            $rs .= "<${typ}>" . strftime("%Y%m%dT%H:%M:%S", $val) . "</${typ}>";
```

**Comment by gggeek** [comment]
Thanks. Fixed in release 4.8.1
