### ISSUE TITLE
Is it possible to disable autpomatic base64 decoding?

### ISSUE THREAD

**Issue by mlewis-everley** [gggeek/phpxmlrpc#112]
Hi All,

Hope this is the best place to ask this?

I am using PHPXMLRPC to handle a data feed coming from a third party site. Sometimes this feed contains image data that is base64 encoded. The system that takes this image data can handle base64 image data and can use that to generate an image on our server, but currently PHPXMLRPC appears to be converting the base64 encoded data into binary data.

As the subject states, is it possible to do this? I have been reading through the docs, the API docs and the sourcecode and I cannot see an obvious way. Possibly I need to write my own version of `XMLParser` or `Encoder` (that extend the original classes) and use those?

**Comment by gggeek** [comment]
Hello.

Atm, there is no knob to be turned which would allow library users to get back the original base64 data without decoding it. To be honest, in the many years I maintain it, no one before requested such a feature, but I see that it could be useful for at least one scenario, which is: if you want to save that data in base64 form and decode it later.

The best way to achieve that would indeed be subclassing the `XMLParser` class and override the `xmlrpc_ee` method. You would then have to create an instance of your own class and inject it into all the parser-aware classes - similar to what is done in `PhpXmlRpc::setLogger` - in fact, I think I could at least provide courtesy methods `setParser` and `setEncoder`...

**Comment by gggeek** [comment]
ps: to be more clear: we could add this feature to the base library, and keep it disabled by default. But I am loath to add more configurable settings to make the behaviour of the decoding part over-flexible. In fact, there are probably too many already. And, as I said, this requirement does not seem to be very common...

**Comment by mlewis-everley** [comment]
Thanks for the response, I hadn't really envisioned this as a feature request, more as a general question. I can see this is probably more of an edge case scenario than a core requirement :-).

I am perfectly happy with the injection workflow if that is the preferred/intended approach, but looking at `Encoder` it appears to implement `ParserAware`, which in turn uses `setParser` (https://github.com/gggeek/phpxmlrpc/blob/master/src/Traits/ParserAware.php#L24). Could I just use that? Or am I missing something?

**Comment by gggeek** [comment]
Sure, you can inject a custom XMLParser in the Encoder using a single call to the existing `setParser` method. I was just proposing to add a `PhpXmlRpc::setParser` method which could be used to inject the custom parser into all classes making use of it, which, for the client case, are both Encoder and Request.

**Comment by mlewis-everley** [comment]
Ahhhhh, I see. That makes sense, a global setting might be handy, for now though I can probably work with setting the parser on Encoder (hopefully). I guess you can probably close this?

**Comment by gggeek** [comment]
Ok, closing
