### ISSUE TITLE
Struct does not work

### ISSUE THREAD

**Issue by powerdan** [gggeek/phpxmlrpc#113]
Hi,

I am struggling getting an struct to work. I used to build it manually and now i am trying to use the Encoder. Did i miss something obvious here?

```       
        var_dump($arguments);
        $encoder = new Encoder();
        $request = new Request($name, $encoder->encode($arguments));
        $xmlResult = $this->xmlrpc->send($request);
        var_dump($request->payload);
```

Will get the following Response:

```
array(5) {
  ["company"]=>
  string(9) "betreiber"
  ["encrypted"]=>
  string(1) "n"
}
XML-RPC: PhpXmlRpc\Helper\Http::parseResponseHeaders: HTTP error, got response: HTTP/2 500 
string(376) "<?xml version="1.0"?>
<methodCall>
<methodName>tickets_session_init</methodName>
<params>
<param>
<value><string>betreiber</string></value>
</param>
<param>
<value><string>n</string></value>
</param>
</params>
</methodCall>"
```

My expectation would be that i should see the structs when dumping the $request->payload but somehow it does not work...

I am using PHP 8.2.6 and 4.10.1 of the lib.

Best
Daniel

**Comment by powerdan** [comment]
(The HTTP 500 of the XMLRPC Server is expected because the lib does not provide a struct)

**Comment by powerdan** [comment]
Okay, my mistake

```
        $encoder = new Encoder();
        $request = new Request($name, new Value($encoder->encode($arguments)));
```

is working. Thank you!

**Comment by gggeek** [comment]
Your mistake is that the constructor of `Request` takes an array of `Value` elements, not a single one.

The "good" code that you posted above works in fact by coincidence (the lib's usage of duck typing): the code will iterate over the single `Value` you pass in, and `Value` does behave like an array.

The correct version is:

```
$request = new Request($name, [$encoder->encode($arguments)]);
```
