### ISSUE TITLE
Cannot access protected property Server::accepted_charset_encodings in Server.php (1533)

### ISSUE THREAD

**Issue by melbawab** [gggeek/phpxmlrpc#115]
I am running in to an error using the latest version 4.10.1 with PHP 8.2, The error occurs each time we try to serve a request, complaining that Server::accepted_charset_encodings is protected properties

`Cannot access protected property Server::accepted_charset_encodings in phpxmlrpc/vendor/phpxmlrpc/phpxmlrpc/src/Server.php'

PHP 8.2.7
Debian 12 (Bookworm)
phpxmlrpc: version 4.10.1
Apache 2
Running PHP as a FPM

The error does not occur in version 4.9.5

**Comment by gggeek** [comment]
Hello.

Indeed, `accepted_charset_encodings` has been deprecated in version 4.10.0 - it was mentioned in the NEWS file.

It is not used for any purpose by the Server class, and has in fact been left in only as BC courtesy - with the caveat that warning is emitted whenever it is accessed.
The warning should not be emitted at all, unless `accepted_charset_encodings` is manipulated by a subclass of `Server`.
This should allow users of the library to either fix their code, or silence the warning instead.

Do you know if in your case there is a subclass of `Server` in use, or any other custom code trying to access `accepted_charset_encodings`?

**Comment by melbawab** [comment]
Thanks for the clarification.
I have not subclassed the server class, Using the plain implementation, but I do set the accepted_charset_encodings. Should I just remove this line?

`  $server = registerDispachImp();`
`  if(is_null($server)){`
`    $error_msg = "registerDispachImp() failed";`
`    $status_code=500;`
`    throw new UserException($error_msg,CRITICAL_CODE,get_defined_vars());`
`  }`
`  $server->accepted_charset_encodings = array('UTF-8', 'ISO-8859-1', 'US-ASCII');`
`  // 2 = allow the exception to float to the upper layers`
`  $server->exception_handling = 2; `
`  $server->debug=0;`
`  $server->service(); `

**Comment by gggeek** [comment]
yes, just remove that line
