### ISSUE TITLE
Response sent on Request if HttpException, status_code is false configured.

### ISSUE THREAD

**Issue by fklee** [gggeek/phpxmlrpc#119]
When a HttpException is catch in `phpxmlrpc/phpxmlrpc/src/Request.php` line 250, the $httpResponse parameter is not initialized correctly : 
it is : `array('raw_data' => $data, 'status_code', $e->statusCode())`
and it should be : `array('raw_data' => $data, 'status_code' => $e->statusCode())`

`'status_code'` is the key and `$e->statusCode()` the value.

How to reproduce :
send an error to your client and debug httpResponse() it is something like this at the end :
```
  "headers" => []
  "cookies" => []
  "raw_data" => "..."
  "status_code" => null
  0 => "status_code"
  1 => "429"
```
And should be :
`  "status_code" => "429"`

**Comment by gggeek** [comment]
Closed in rel 4.10.4, thanks
