### ISSUE TITLE
Document Build errors

### ISSUE THREAD

**Issue by jimoe666** [gggeek/phpxmlrpc#22]
linux v3.16.7-7-desktop x86_64
php v5.6.1
phpxmlrpc-master downloaded from current set

I attempted to "make doc" the docs. 

In convert.php I needed to change
```
$proc->setSecurityPreferences(XSL_SECPREF_CREATE_DIRECTORY | XSL_SECPREF_WRITE_FILE);
```
to
```
$proc->setSecurityPrefs(XSL_SECPREF_CREATE_DIRECTORY | XSL_SECPREF_WRITE_FILE);
```
Then, a missing support file:
.../tools/docbook-xsl/xhtml/chunk.xsl
```
Starting xsl conversion process...
PHP Warning:  XSLTProcessor::importStylesheet(): I/O warning : failed to load external entity "/home/jmoe/dev/tools/docbook-xsl/xhtml/chunk.xsl" in /home/jmoe/dev/php/phpxmlrpc-master/doc/convert.php on line 39
PHP Warning:  XSLTProcessor::importStylesheet(): compilation error: file /home/jmoe/dev/php/phpxmlrpc-master/doc/custom.xsl line 14 element import in /home/jmoe/dev/php/phpxmlrpc-master/doc/convert.php on line 39
PHP Warning:  XSLTProcessor::importStylesheet(): xsl:import : unable to load /home/jmoe/dev/tools/docbook-xsl/xhtml/chunk.xsl in /home/jmoe/dev/php/phpxmlrpc-master/doc/convert.php on line 39
PHP Warning:  XSLTProcessor::transformToXml(): No stylesheet associated to this object in /home/jmoe/dev/php/phpxmlrpc-master/doc/convert.php on line 54
OK
```

**Comment by gggeek** [comment]
About setSecurityPreferences vs. setSecurityPrefs: I am sure I had put that there inside an already hackish 'if' because it would not work otherwise...
setSecurityPreferences is not in the online php manual, but I have found it used in at least 2 projects on github.
So I will add a 2nd 'if'...
NB: I do not plan to release a new version in the 3.0 series, so the fix will be in the 4.0 line

**Comment by gggeek** [comment]
As for the missing .../tools/docbook-xsl/xhtml/chunk.xsl file:

the conversion process relies on having a copy of the xsl files available from the docbook-xsl project (http://sourceforge.net/projects/docbook/)

I'm reluctant to include it wholesale in the lib, as it is biggish, can not be installed via composer (afaik) and follows its own independent update schedule. So I just download it manually and keep it available on the box where I do the builds.

Possible fix 1: document this requirement better

Possible fix 2: make the doc generation process download the required xslt automatically if needed (ideally after asking the user if  it is already available somewhere on the system)

**Comment by gggeek** [comment]
About installing the docbook xsl via composer: this is actually possible.
I am not sure if it would conflict with a version installed, say, via apt-get, though.
And other tools used in the doc generation process, such as FOP, might be harder to install this way...

**Comment by jimoe666** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 02/21/2015 03:04 PM, Gaetano Giunta wrote:
> As for the missing .../tools/docbook-xsl/xhtml/chunk.xsl file:
> 
I downloaded <docbook-xsl-1.78.1>.
The file <docbook-xsl/xhtml/chunk.xsl> does not exist in the
distribution.

- -- 
James Moe
moe dot james at sohnen-moe dot com
520.743.3936
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlTpcGMACgkQzTcr8Prq0ZMjOwCfa+VF/RHGoIoApetAZdi+h8pG
RkIAn1rzSZKdSuj8Kv80v5LbwCBxz8TB
=4S7x
-----END PGP SIGNATURE-----

**Comment by gggeek** [comment]
Mmm, not sure what you got, but in docbook-xsl-1.78.1.tar.bz2, there is definitely html/cunk.xsl ...

**Comment by jimoe666** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 02/22/2015 09:13 AM, Gaetano Giunta wrote:
> Mmm, not sure what you got, but in docbook-xsl-1.78.1.tar.bz2, 
> there is definitely html/cunk.xsl ...
> 
  Okay. I had download the ZIP archive. The two archives are
apparently NOT the same. The bzip2 archive does have the coveted XSL file.

- -- 
James Moe
moe dot james at sohnen-moe dot com
520.743.3936
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlTuTWIACgkQzTcr8Prq0ZMXKQCgjvhkkYjJm32Kr1H9+wXHzjtP
Ks4An1VsM81Vd56/BZuvRq90UWC5Ip3s
=llZo
-----END PGP SIGNATURE-----

**Comment by gggeek** [comment]
SInce you did not come back with further feedback for 3 weeks, I assume that you were able to generate the manual.

Can this bug be closed?

**Comment by gggeek** [comment]
No response for a month, closing
