### ISSUE TITLE
Null => Nill value

### ISSUE THREAD

**Issue by HMAZonderland** [gggeek/phpxmlrpc#26]
I'm using the 53 brach and I ran into this weird bug. I created a request with a null value:
```xml
<?xml version="1.0"?>
<methodCall>
   <methodName>Article.ArticleList</methodName>
    <params>
         <param>
                <value><string>H3nrqsEQnT4Dj5R6jlAXzLJZE8knj0yWGpIHarat</string></value>
         </param>
          <param>
                <value><int>1</int></value>
          </param>
          <param>
             <value><nil/></value>
          </param>
          <param>
                <value><int>0</int></value>
          </param>
          <param>
                <value><int>0</int></value>
          </param>
          <param>
               <value><string>id</string></value>
          </param>
          <param>
                <value><string>ASC</string></value>
          </param>
    </params>
</methodCall>
```
Executing this call returns me this error:
```xml
<?xml version="1.0"?>
<methodResponse>
    <fault>
     <value>
        <struct>
           <member>
               <name>faultCode</name>
                <value><int>15</int></value>
            </member>
            <member>
                <name>faultString</name>
                <value><string>Invalid request payload found not-xmlrpc xml element NIL</string></value>
            </member>
         </struct>
      </value>
     </fault>
</methodResponse>
```
Checking the code that belongs to these checks I discovered that the `$xmlrpcNull` gets transformed to `<nil>` in the `Value` class `serializedata()` function:
```php
case static::$xmlrpcNull:
    if (PhpXmlRpc::$xmlrpc_null_apache_encoding) {
        $rs .= "<ex:nil/>";
    } else {
        $rs .= "<nil/>";
    }
    break;
```
In the `XMLParser` class I found the `xmlrpc_se` function that parses the Xml, however, claims these variables are not yet supported? Or won't be supported. 
```php
case 'NIL':
case 'EX:NIL':
    if (PhpXmlRpc::$xmlrpc_null_extension) {
        if ($this->_xh['vt'] != 'value') {
            //two data elements inside a value: an error occurred!
            $this->_xh['isf'] = 2;
            $this->_xh['isf_reason'] = "$name element following a {$this->_xh['vt']} element inside a single value";

            return;
        }
        $this->_xh['ac'] = ''; // reset the accumulator
        break;
    }
// we do not support the <NIL/> extension, so
// drop through intentionally
default:
    /// INVALID ELEMENT: RAISE ISF so that it is later recognized!!!
    $this->_xh['isf'] = 2;
    $this->_xh['isf_reason'] = "found not-xmlrpc xml element $name";
    break;
```
How do I send my `null` value around? As a string?

PS: I'm also wondering if the `break` of the `NIL` and `EX:NIL` case is in the right place?

**Comment by HMAZonderland** [comment]
My bad, I guess overlooked something. I had to set `PhpXmlRpc::$xmlrpc_null_extension = true`

**Comment by gggeek** [comment]
yup :-)

**Comment by gggeek** [comment]
Side note: any feedback on the php53 branch? Things you'd like to see added or changed?

**Comment by HMAZonderland** [comment]
Well I have to say using this branch feels better. I do have to change ALOT of code to be compatible with this, but its for a better cause.

I did find something weird tho. It seems as if the php53 branch RPC => function map is much stricter. I have to add that I did write a class on top of the `Server` class to parse a token I send with each call. 

This used to work (please note, there is a double entry in the signature. I just discovered this as a bug)
```php
'Article.ArticleCount' => array(
    'class' => 'Wiq_ArticleController',
    'function' => 'Article_ArticleCount',
    'signature' => array(
        array($xmlrpcArray, $xmlrpcString, $xmlrpcInt, $xmlrpcInt),
        array($xmlrpcArray, $xmlrpcString, $xmlrpcNull, $xmlrpcNull),
        array($xmlrpcArray, $xmlrpcString, $xmlrpcNull, $xmlrpcInt),
        array($xmlrpcArray, $xmlrpcString, $xmlrpcNull, $xmlrpcInt)
    ),
    'docstring' => '[token] [active] [public]',
    'cache' => true
),
```
Updating to this (please note, bug still there):
```php
'Article.ArticleCount' => array(
    'class' => 'Wiq_ArticleController',
    'function' => 'Article_ArticleCount',
    'signature' => array(
        array(Value::$xmlrpcArray, Value::$xmlrpcString, Value::$xmlrpcInt, Value::$xmlrpcInt),
        array(Value::$xmlrpcArray, Value::$xmlrpcString, Value::$xmlrpcNull, Value::$xmlrpcNull),
        array(Value::$xmlrpcArray, Value::$xmlrpcString, Value::$xmlrpcNull, Value::$xmlrpcInt),
        array(Value::$xmlrpcArray, Value::$xmlrpcString, Value::$xmlrpcNull, Value::$xmlrpcInt)
    ),
    'docstring' => '[token] [active] [public]',
    'cache' => true
),
```
Now the Server responded with `Incorrect parameter count` when sending: `Article.ArticleCount(1, null)`

**Comment by gggeek** [comment]
Interesting use case -  I do not think there's any scenario in the test suite which uses xmlrpc null values.
I will try to look over it in the weekend (no promise given though).
Otoh: what about not sending a value at all when it is NULL?
eg:
    'signature' => array(
        array(Value::$xmlrpcArray, Value::$xmlrpcString, Value::$xmlrpcInt),
        array(Value::$xmlrpcArray, Value::$xmlrpcString, Value::$xmlrpcInt, Value::$xmlrpcInt),
        array(Value::$xmlrpcArray, Value::$xmlrpcString, Value::$xmlrpcNull, Value::$xmlrpcInt),
    ),

pps: if you don't wanna go over changing your code, there's still the compatibility layer available...

**Comment by HMAZonderland** [comment]
I wanted to update the code, its time to do some refactoring etc. And it helps to find old bugs.
