### ISSUE TITLE
Converting from raw XML to PHP XML-RPC

### ISSUE THREAD

**Issue by ryanhellyer** [gggeek/phpxmlrpc#28]
I'm having dreadful difficulties getting from very basic raw XML to the syntax used in the PHP XML-RPC script.

I can get from this basic example:
http://pastebin.com/bddsUuaw
To this, very easily:
http://pastebin.com/hbfmBbjg

But for a project I'm working on at the moment, I need to another variable for a limit in place. But I have no idea how to generate this with the PHP XML-RPC syntax and so are instead needing to use raw XML to do it, which doesn't seem very efficient.
Here is the raw XML I'm trying to convert from ... http://pastebin.com/tYWyMWR0

Does anyone know how to do this? Or alternatively, able to point me in the direction of some example code? I've been bashing away on this for days, but am failing miserably :/ Thanks for any help you can provide :)

**Comment by gggeek** [comment]
You could try

```php
$data = new xmlrpcmsg(
        'Some.Service',
        array(
                new xmlrpcval( '1234567890' ),
                new xmlrpcval(array('limit' => new xmlrpcval(2, 'int')), 'struct')
        )
);

**Comment by gggeek** [comment]
PS: I am a bit surprised that you have been struggling with this for so long.
A similar example is given in the manual: http://gggeek.github.io/phpxmlrpc/doc-2/ch07.html#xmlrpcval-creation.

If you think that it looks too archaic/convoluted, there is also a simpler way to do the conversion from php values to xmlrpc values, also documented ( at http://gggeek.github.io/phpxmlrpc/doc-2/ch09s02.html#phpxmlrpcencode )

```php
$data = new xmlrpcmsg(
        'Some.Service',
        array(
                new xmlrpcval( '1234567890' ),
                php_xmlrpc_encode(array('limit' => 2))
        )
);

**Comment by ryanhellyer** [comment]
Yes, I was surprised too! I think my brain just failed to grok it the first time around, and all subsequent attempts missed the blatantly obvious. Thanks for your super quick response :) I haven't had a chance to try it out yet, but will take a look once I'm back at my computer.

**Comment by ryanhellyer** [comment]
This worked flawlessly. Thanks so much for answering my very basic question :)
