### ISSUE TITLE
PhpXmlRpc request

### ISSUE THREAD

**Issue by NourdineMazali** [gggeek/phpxmlrpc#30]
I have this function zyyne.listLoad(X), Can anyone PLEASE show me how I can get results using PhpXmlRpc, I read the documentation twice but couldn't get my head around it

**Comment by gggeek** [comment]
Hello.

I read your message twice but I have definitely not enough information about what you want to accomplish ;-)

**Comment by NourdineMazali** [comment]
HI.
Well I basically want to execute this function zyyne.listLoad(N) which return a list of items this is my code : 
\PhpXmlRpc\Autoloader::register();
$client = new \PhpXmlRpc\Client("/services/xmlrpc","zyyne.com",80);
$client->setCredentials('_________','___________');

**Comment by gggeek** [comment]
So far so good. Then:

$value = new \PhpXmlRpc\Value($N, "integer");
$response = $client->send(new \PhpXmlRpc\Request('zyyne.listLoad', array($value)));
$data = $resp->value();

PS: I am sorry about the manual not being up to date with the current version of the code. You can find a lot of examples in the 'demo' folder inside the library, which might be helpful.

**Comment by NourdineMazali** [comment]
Thanks for your prompt reply ,U have been a great help for me, although any idea why I only get the first item of the list.
Thank you again

**Comment by gggeek** [comment]
No idea why you get only 1 item out of a list.
You can enable debug on the client object to check the xml which it has received to verify if it is indeed a list or not...

**Comment by NourdineMazali** [comment]
How can I enable it @gggeek ?

**Comment by gggeek** [comment]
$client->setDebug(2);

**Comment by NourdineMazali** [comment]
Thank you enormously @gggeek

**Comment by gggeek** [comment]
Seems like we can close :-)
