### ISSUE TITLE
Automatic decoding of UTF8 within response body?

### ISSUE THREAD

**Issue by kamelkev** [gggeek/phpxmlrpc#31]
I'm currently adding UTF8 support for a library I maintain, which happens to use your very nice library.

I've noticed a quirk however. It seems that the library is automatically decoding all utf8 characters, even when I don't want it to. I've tried setting the globals for xmlrpc_defencoding and xmlrpc_internalencoding to US_ASCII, as I figure that's the least likely mode to alter my response body, but it's still decoding the utf8 bytes.

To autodetect the utf8 and decode them despite this top level setting being set to ASCII seems wrong. Am I missing something here?

Thanks in advance, and for your great work on this package.

EDIT> This is coincidentally part of WordPress, now wondering if somehow the library is taking cues from some sort of global related to mb_internal_encoding.

**Comment by gggeek** [comment]
Sorry for not noticing the issue earlier, mail must have fallen through the cracks.

The way to have the lib NOT mangle utf8 when passing it from the external caller to your application is in fact to set xmlrpc_internalencoding to utf8 :-)

**Comment by gggeek** [comment]
ps: WP afaik has replaced usage of this lib eons ago, and now has its own implementation of xmlrpc.
Not that I want to discourage use of my baby, but are you sure you should not be using the built-in functionality (if available)?

**Comment by kamelkev** [comment]
Hi Gaetano,

I did eventually figure this out. The source of the issue appeared to be inconsistent XML character encoding headers. Basically you need both sides saying UTF8. Your library can and does do everything as it's supposed to, I just had a configuration problem, which I figured out after a bunch of trial and error.

We use your library within a Wordpress plugin. There are certainly other options out there, but why mess with a good thing :)

thanks for the reply
