### ISSUE TITLE
Fault code: [5] Reason: 'Didn't receive 200 OK from remote server. (HTTP/1.0 403 Forbidden)'

### ISSUE THREAD

**Issue by custard-apple** [gggeek/phpxmlrpc#34]
Hey I'm newbie here in xmlrpc, I'm trying to request the server  but its not connecting...

**Comment by gggeek** [comment]
Ok, there are a lot of chances that you might be using the wrong url, or that the server might be set up wrong.

0 which version of the lib are you using?

1. Are you developing the server-side as well, or only the client?

2. can you paste the code of your client?

3. in the code, after you create the client, try adding:

$client->setDebug(2);

this should give you a lot of details about http communication

**Comment by custard-apple** [comment]
I'm working on client side only & using  xmlrpc.inc,v 1.174 .

**Comment by custard-apple** [comment]
Sorry but I cant share my client code...

**Comment by gggeek** [comment]
If you can't share the bit of code where the client object is created, all I can tell you is what I said above: use the `setDebug` call.
Is the xmlrpc server that you are using a public one, so that I could test accessing it?

**Comment by custard-apple** [comment]
Whenever I type The url in browser, I got this result <CallCenterResult>RequestFormatInvalid</CallCenterResult>
But when I fire it into "http://gggeek.altervista.org/sw/xmlrpc/debugger/" I got that Fault code error..

**Comment by custard-apple** [comment]
Ok. I'll share my client code.
here is the link from where I got my client code in Answer 1.Let me know what can I modify.
http://stackoverflow.com/questions/22832089/xml-rpc-connection-using-php

**Comment by custard-apple** [comment]
`--SENDING--- POST / HTTP/1.0 User-Agent: XML-RPC for PHP 3.0.0.beta Host:"myserveraddress"  Accept-Encoding: gzip, deflate Accept-Charset: UTF-8,ISO-8859-1,US-ASCII Content-Type: text/xml; charset=UTF-8 Content-Length: 94 <?xml version="1.0" encoding="UTF-8" ?> <CallCenterRequest>GetAllCustomers</CallCenterRequest> ---END--- 
xmlrpcresp Object ( [val] => 0 [valtyp] => [errno] => 5 [errstr] => Connect error: Connection timed out (110) [payload] => [hdrs] => Array ( ) [_cookies] => Array ( ) [content_type] => text/xml [raw_data] => )`

**Comment by custard-apple** [comment]
This is the output when I use $client->setDebug(2);

**Comment by gggeek** [comment]
So, It seems that you are contacting http://myserveraddress - and that it is not responding.
Is this the correct url for the server?

**Comment by custard-apple** [comment]
I cant send you IP so I send Dummy address

**Comment by custard-apple** [comment]
My server address showing fault code

**Comment by gggeek** [comment]
So, let me try to get this straight :-)

- you copied the code from an example mentioning Adestra, but your target server is not Adestra, correct?

- in the title of the ticket, you mention 'error 403', but in the debug log that you showed me there is a timeout error, which is different...

- q: do the docs for your server mention the fact that you need basic auth or ntlm auth?

**Comment by custard-apple** [comment]
- Right.my target is not Adestra

- When I test this URL on debugger I got 403 error But when I implement it with XMLRPC library I got timeout error.

- No I don't need auth

**Comment by gggeek** [comment]
Bizarre. Is there any authentication mechanism in place at all, based on IP validation or similar?

**Comment by custard-apple** [comment]
they provide us ip address, port number, username and password, so, I tried to do basic auth from the adestra example which I mentioned above, but still there is no luck to connect, that is it gives connection timeout error after long time of execution, so can you please provide me simple way for the basic auth so that I can connect to the xmlrpc server?

**Comment by custard-apple** [comment]
`<CallCenterResult>RequestFormatInvalid</CallCenterResult>`

**Comment by gggeek** [comment]
To set auth credentials, the recmmended way is not to put them in the url, but to do:

`$client->setCredentials();`

**Comment by custard-apple** [comment]
What auth type should I provide?

**Comment by gggeek** [comment]
I see that you seem to have fixed the auth problem :-)

Otoh the anser you get is a bit weird: `<CallCenterResult>` makes me think that the server might not be using xml-rpc protocol, but just REST calls with XML format, or maybe SOAP...

**Comment by custard-apple** [comment]
Can you please suggest me what should I do exactly to get the data of method define on the xmlrpc server?

**Comment by gggeek** [comment]
auth type 1 for basic auth

**Comment by gggeek** [comment]
I have no idea what the specs are for your system.
You should talk to the person who developed the server and ask him/her for some documentation.

**Comment by custard-apple** [comment]
ok.Thank you so much for such infomation.
