### ISSUE TITLE
XML error: Invalid document end at line 3, column 2096984

### ISSUE THREAD

**Issue by DianonForce** [gggeek/phpxmlrpc#35]
Hi, 
i have a working XML-RPC client connection with our server. As long as i only rquest a few data, everything is fine, but if i request a large ammount of data, i ever get the same error.

```
Code: 2
Reason: 'Invalid return payload: enable debugging to examine incoming payload (XML error: Invalid document end at line 3, column 2096984)'
```

No matter, wich method i use, as long as the response is a larger dataset, this error occure.
I tried diffrent servers (Synology Nas, Xammp on my pc) and also tried diffrent connections (cabel- and mobilenetwork), so i don't think it's a network problem. 
I also run a wireshark on the connection. It looks like the client close the connection after some time.

I don't know if this is a error in the script or a miss configuration of my php/apache, maybe you can point my nose at the right .

**Comment by gggeek** [comment]
It might be different things: timeouts, or php running out of memory. I think that if it was an out-of-memory, you would not see the end of the php script.

Is the xmlrpc-server you are testing against a public one, so that I might investigate as well?

ps: I surmise that you are setting a high value to the timeout parameter of the 'send' call ?

**Comment by DianonForce** [comment]
i tried a '360' timeout at the 'send' call, but it make no diffrence in the respond. I also tried default_socket_timeout = 360 in my php.ini.

The xmlrpc-server is public reachable, but you need to call a login method to call further method's.

**Comment by DianonForce** [comment]
I do a little testing with phpxmlrpc and a script that the Admin from the xmlrpc-server gave me.
With phpxmlrpc i run in the error, with the script it respond a complete lenght of 78874 bytes. So it seems to be an issue in phpxmlrpc.

**Comment by DianonForce** [comment]
Ok, many hours later, the mystery is solved. 

i missed the method parameter in the 'send' call.
