### ISSUE TITLE
i8 type support

### ISSUE THREAD

**Issue by Tuxity** [gggeek/phpxmlrpc#37]
Hi,

I'm working with a feed I can't change, and I've this error `Invalid return payload: enable debugging to examine incoming payload xmlrpc element I8 cannot be child of VALUE` because in my returning xml have `<value><i8>196665</i8></value>` in it.

Can't we support the i8 type in the project ?

**Comment by gggeek** [comment]
It seems that i8 support was never added to the lib.

This is an old ticket where this was requested: https://sourceforge.net/p/phpxmlrpc/bugs/78/

I guess that php 64-bit is more widespread now, adding support for i8 is not a huge problem.

It still would need a few hours of hacking and adding in tests though, and I am pretty busy at the moment, so I can not guarantee anything.

Any contribution is of course welcome :-)

**Comment by Tuxity** [comment]
Ok, I've begin the support for i8 type in my fork, gonna do some tests in my project and I'm gonna do a pull request asap.
