### ISSUE TITLE
PhpXmlRpc\Encoder::encode error

### ISSUE THREAD

**Issue by reinos** [gggeek/phpxmlrpc#39]
Calling the method `PhpXmlRpc\Encoder::encode` gives me the following error:

`Fatal error: Call to undefined method Webservice_testing_tool::encode() in /Users/reinos/Sites/svn-migrate/EE/webservice/ee2/system/expressionengine/third_party/webservice/vendor/phpxmlrpc/phpxmlrpc/src/Encoder.php on line 167`

After inspecting the method `encode` in file `Encoder.php` i saw that this method calls himself with `$this->`. After changing that to `self::` the error is gone and the encoding works again.

My code:
```php
$c = new PhpXmlRpc\Client(ee()->input->post('path'));

$x = new PhpXmlRpc\Request($_POST['method'], array(
	PhpXmlRpc\Encoder::encode(array(
		'session_id' => ee()->session->userdata('session_id')
	)),
	PhpXmlRpc\Encoder::encode($this->format_data()),
));

$c->return_type = 'phpvals';
$r =$c->send($x);

return $r;
```

**Comment by reinos** [comment]
But i think thats not the solution, since PHP7.x give me this error when testing it.

`Non-static method PhpXmlRpc\Encoder::encode() should not be called statically`

It works fine in a lower version then PHP 7.x

**Comment by gggeek** [comment]
Indeed, the Encoder class now has non-static methods.

Your code should 1st create an Encoder object, then use the method, as done here: https://github.com/gggeek/phpxmlrpc/blob/master/demo/client/getstatename.php#L16
