### ISSUE TITLE
2 calls to undefined php_xmlrpc_encode() function in Server.php

### ISSUE THREAD

**Issue by cmanley** [gggeek/phpxmlrpc#41]
This fixes it:

On line 678, replace:
$r = new Response(php_xmlrpc_encode($r, array('extension_api')));
with:
$encoder = new Encoder();
$r = new Response($encoder->encode($r, array('extension_api')));

On line 688, replace:
$r = new Response(php_xmlrpc_encode($r, $this->phpvals_encoding_options));
with:
$encoder = new Encoder();
$r = new Response($encoder->encode($r, $this->phpvals_encoding_options));

**Comment by gggeek** [comment]
Fixed in 4.1.1. Thanks!
