### ISSUE TITLE
difficulties in enabling the xmlrpc_null_extension feature

### ISSUE THREAD

**Issue by parmentelat** [gggeek/phpxmlrpc#45]
Hi there

I need to send out xmlrpc calls (from php to python) with some NULL inside the arguments.
WIthout doing anything particular, when calling e.g.
`GetPersons(array('peer_id' => NULL))`
I receive at the python end
`GetPersons({'peer_id' : []})`
but I need to receive of course
`GetPersons({'peer_id' : None})`

My understanding was that I could get this to work for me by just setting these

```
$GLOBALS['xmlrpc_null_extension'] = true;
$GLOBALS['xmlrpc_null_apache_encoding'] = true;
```

but from what I see in my set up, these settings have no effect.

So I guess my question is: should the librarry behave as I expect it to, or am I misunderstanding the feature ? In particular at some point I wondered if that `<nil/>` business would be only recognized on the way back from the call ? 

Anyway, thanks :)

**Comment by gggeek** [comment]
Hello.

Here is a snippet of code that should get you going:

```
$val = array('peer_id' => null);
$encoder = new PhpXmlRpc\Encoder();

var_dump($encoder->encode($val, array('null_extension'))->serialize());

PhpXmlRpc\PhpXmlRpc::$xmlrpc_null_apache_encoding = true;
var_dump($encoder->encode($val, array('null_extension'))->serialize());
```

In short:
- xmlrpc_null_extension is for decoding received data
- null_extension is for encoding data to be sent
- xmlrpc_null_apache_encoding is for using <ex:nil> instead of <nil/> in the generated xml

**Comment by parmentelat** [comment]
Hey - thanks for the feedback

can I expect to use this instead then ?

```
xmlrpc_encode_request($method, $args, array('null_extension'));
```

my first attempts seem to say that it won't work, but I need to double check that more thoroughly, so in the meanwhile I thought you would maybe know the answer :)

thanks for the tip in any case

**Comment by gggeek** [comment]
I had to check the source code in order to be able to answer: the `xmlrpc_encode_request` method is not part of the core library and has not been updated in a long time...
In fact it is only provided as helper for people who have to run an app built on top of the php native xmlrpc extension on servers where that extension can not be installed.
In other words:
while it would not take a long time to add support for the 'null_extension' option as 3rd parameter in the xmlrpc_encode_request method, I see little point in doing this, as this is not an option that is supported by the native phpxmlrpc extension. We would not be increasing compatibility.

Maybe we could think about improving the native lib API to make it easier to achieve an equivalent one-liner? f.e. we could add a 3rd 'options' param to the Request class...

**Comment by parmentelat** [comment]
thanks for the feedback

just for a little more context:
* this is about maintaining a very old piece of code
* it used to be running on a patched version of phpxmlrpc, that won't build anymore on modern fedoras
* so I've decided to go with the mainstream package - this is probably long overdue
* also it turns out I have a single line that needs to be tweaked
* and finally it is fair to say that I have totally forgotten about the little I had grasped about the internals of phpxmlrpc in the 10years+ meanwhile ;)

so in principle this is all fine by me, it's no big deal either way (that we come up with the oneliner or not)

however, short of digging much deeper into all this, I couldn't see right away how I could work around the issue on my own

in case you'd have 2 minutes to look at the specifics, here's the link to the code in question
http://git.onelab.eu/?p=plcapi.git;a=blob;f=php/plc_api.php#l145

let me know if/what it inspires you

thanks again in any case

**Comment by gggeek** [comment]
Took a look at your code. Not sure it's worth going through a complete revamp ;-)

So, contrary to what I previously stated, I just went and added support for `xmlrpc_encode_request($method, $args, array('null_extension'));`

It is available in the newly released version 0.6 of the extras package. Could you please test it?

**Comment by parmentelat** [comment]
Thanks ! I am more than willing to test this, of course :)

However my exposure to php really is very low, esp. when it comes to software distribution, and as far as php goes, I'm only familiar with installing fedora's rpms...
I've taken a look at INSTALL.md but that wasn't exactly helpful given my current skills.
Also given that this repo has not been changed recently, I take it we're talking about some other place, right ?
So I guess could use a little more details on how I should go about conducting this test, otherwise I'm afraid my results would turn out inconclusive. 

thanks again

**Comment by gggeek** [comment]
Where to find the software:
- yes, the pure-php implementation of the `xmlrpc_encode_request` method is not part of this library, you will find it in https://github.com/gggeek/phpxmlrpc-extras
- phpxmlrpc-extras depends on phpxmlrpc, so you will need to have both packages installed

How to install it:
- "modern" php applications use Composer to manage dependencies. It is a very good tool, but it comes with a bit of a learning curve. In short: you would have to add a composer.json file in the top dir of your application, where you declare your dependencies, then download composer itself and run `composer install`. If the libraries you depend on are OOP, you will get proper class autoloading set up for you, which is nice. If not, you would also need to make sure that you set up manually the inclusion of the library files from your code
- as an alternative: you can download both phpxmlrpc and phpxmlrpc-extras by hand, and unzip them somewhere - typically in a subir of your app - and set up manually all the class autoload paths and library file inclusions

**Comment by gggeek** [comment]
More than 6 months without an update. Closing.

**Comment by parmentelat** [comment]
Thank you you have been very helpful :)
