### ISSUE TITLE
ERROR:  Failed to parse XML-RPC request: Invalid byte 1 of 1-byte UTF-8 sequence

### ISSUE THREAD

**Issue by infusedmj** [gggeek/phpxmlrpc#47]
At some point in my app, I get an error saying

Failed to parse XML-RPC request: Invalid byte 1 of 1-byte UTF-8 sequence

I went back to xmlrpc 3.0 version and I didn't receive such error.
It only happens to 4.0. It happens when I have this text encoded:

Media Mail (USPS) – 2-8 days

All of the text above are all UTF-8. Not sure why is this happening? 
Any thoughts? Right now I went back to 3.0 but it shows up deprecated errors in PHP 7.

I appreciate any insights on this.

**Comment by gggeek** [comment]
Hello.

Could you give me some more details to help reproduce the issue?
- are you using phpxmlrpc as client, server, or both?
- does the error happen when the lib is encoding data (received from your app) or decoding it (received from the network partner)?
- what is the internal encoding of data for your app?
- do you change the value for the external encoding to be used by the lib or leave it at default?

**Comment by infusedmj** [comment]
Thank you for the fast response!

1. I am using it as a client only as I connect it to an API (infusionsoft)
2. Yes - it happens when lib is encoding data, that is php_xmlrpc_encode() is invoked
3. UTF-8
4. It is set to default and didn't change the external encoding.

**Comment by gggeek** [comment]
I tried with the test file below, and I can not reproduce the error.
I think that you will need to
- tell me the version of php you use, and whether mbstring is enabled (and if so, how is it configured)
- dump the source string in a way that we can inspect the single bytes that make it up

Here is my test:
```
<?php

// assumes this to be saved as utf8

include('./lib/xmlrpc.inc');

// wrong: lib assumes internal charset is latin-1
$string = 'Media Mail (USPS) – 2-8 days';
var_dump(php_xmlrpc_encode($string)->serialize());

// wrong: the original string is already in utf8 (depending on how you save this file of course)
$string = utf8_encode('Media Mail (USPS) – 2-8 days');
$GLOBALS['xmlrpc_internalencoding'] = 'UTF-8';
PhpXmlRpc\PhpXmlRpc::importGlobals();
var_dump(php_xmlrpc_encode($string)->serialize());

// correct
$string = 'Media Mail (USPS) – 2-8 days';
$GLOBALS['xmlrpc_internalencoding'] = 'UTF-8';
PhpXmlRpc\PhpXmlRpc::importGlobals();
var_dump(php_xmlrpc_encode($string)->serialize());
```

**Comment by gggeek** [comment]
Is this still relevant?

**Comment by gggeek** [comment]
Ping

**Comment by gggeek** [comment]
Closing as this has been left without updates for two years. Feel free to reopen if needed
