### ISSUE TITLE
Feature request: make less specific date type detection in Encoder::encode

### ISSUE THREAD

**Issue by FinesseRus** [gggeek/phpxmlrpc#50]
The `Encoder::encode` method detects a date by checking whether it is a `DateTime` instance. The `DateTime` class implements the `DateTimeInterface` interface which also supports the `format` method.

So I suggest to change `DateTime` to `DateTimeInterface` to make a `DateTimeImmutable` object also be detected as a date.

If you agree, I can make a pull request.

**Comment by gggeek** [comment]
Seems like a good idea. All we use from that object is the 'format' methopd, so I see no downsides.
PR welcome

**Comment by FinesseRus** [comment]
@gggeek Pull request is ready: https://github.com/gggeek/phpxmlrpc/pull/51

**Comment by gggeek** [comment]
PR merged, will be in next release

**Comment by FinesseRus** [comment]
@gggeek Thanks!
