### ISSUE TITLE
Not able to create autoload classes.

### ISSUE THREAD

**Issue by sachind** [gggeek/phpxmlrpc#54]
Hi,

Its a good piece of code and worked very well in regular RPC operations. Recently I was trying to upgrade PHP 7 and ultimately would like to upgrade XML RPC libraries from 2.0.1 to 4.0.1. 

But while trying to compile composer, I have encountered following error. I have copy the steps from the windows command prompt.

C:\svn\Sample\phpxmlrpc>php composer.phar require phpxmlrpc/phpxmlrpc:4.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package phpxmlrpc/phpxmlrpc No version set (parsed as 1.0.0) is satisfiable by phpxmlrpc/phpxmlrpc[No version set (parsed as 1.0.0)] but those are rejected by your minimum-stability.

Installation failed, reverting ./composer.json to its original content.

Please let me know if I missing anything that creating issues while creating composer.

Thanks.

**Comment by HMAZonderland** [comment]
I think you defined the version number incorrectly; `php composer.phar require phpxmlrpc/phpxmlrpc:4.*`

**Comment by HMAZonderland** [comment]
@sachind did it work?

**Comment by murraycollingwood** [comment]
Can I join this thread?
I installed via composer:  "phpxmlrpc/phpxmlrpc": "4.0.*"
I am using other libraries installed via composer and they work fine.
This code:
include "../vendor/autoload.php";
$client = new xmlrpc_client("/", "http://rpc.pingomatic.com/", 80); 
Results in:
Fatal error: Class 'xmlrpc_client' not found in /Users/murray/dev/sobs-git/trunk/build/liss/testclient.php on line 11

**Comment by gggeek** [comment]
@murraycollingwood the thing is that the API is completely different between v3 and v4. But we have a shim that basically still exposes v3 API on top of the v4 classes.

For legacy code (which uses v3 api): keep your code as is, but you will need to manually include the xmlrpc.inc and xmlrpcs.inc files as it was done ages ago.
Foir new code: pleae use the v4 API that, as you have already found out, uses namespaces and gets autoloaded fine.

**Comment by gggeek** [comment]
As for your last question: a simpler (or just plain different) way of using namespaces to keep your code both succint and readable:

```
use PhpXmlRpc\Client as PXRClient;
use PhpXmlRpc\Request as PXRReq;
use PhpXmlRpc\Value as PXRVal;

...

client = new PXRClient("http://rpc.pingomatic.com/");
$message = new PXRReq("weblogUpdates.ping",array(new PXRVal(1, "int")));
```

**Comment by gggeek** [comment]
4 months and no feedback. Closing :-)
