### ISSUE TITLE
PHP 7.2 compatibility issue

### ISSUE THREAD

**Issue by montaniasystemab** [gggeek/phpxmlrpc#55]
In PHP 7.2 (tested with beta 2) there's an issue in the Request class: 

```
count(): Parameter must be an array or an object that implements Countable

/…/vendor/phpxmlrpc/phpxmlrpc/src/Request.php:291
```

In PHP 7.2 you will no longer be able to send strings into `count()` so this needs to be changed in order to support PHP 7.2

Source: https://wiki.php.net/rfc/counting_non_countables

**Comment by HMAZonderland** [comment]
I think PHP7.2  support requires a whole new branch and version of this library. I guess the PHPUnit 5.7.* (which the library is currently capped at due compatibility issues) cannot run on PHP7.1. 

@gggeek I guess supporting PHP7.2 goes hand in hand with #52.

**Comment by gggeek** [comment]
Btw, there's a bunch of other warnings as well, due to 'each' being deprecated...

**Comment by gggeek** [comment]
Fixed in 4.2.1

**Comment by glensc** [comment]
@gggeek this issue is mentioned in 4.3.0 changelog: https://github.com/gggeek/phpxmlrpc/releases/tag/4.3.0

> fixed: compatibility with Basic/Digest/NTLM auth when using client in cURL mode (issue #55)


but this has nothing to do with digest or curl mode. wrong ticket id in release notes?

**Comment by gggeek** [comment]
Thx for noticing, fixed the NEWS file. The correct ticket number is #58

**Comment by glensc** [comment]
please edit the release in github as well. thanks

**Comment by gggeek** [comment]
done

**Comment by sougatabose07** [comment]
I am having issue with each() too.

The each() function is deprecated. This message will be suppressed on further calls

For - 

`list($typ, $val) = each($this->me);`

In - 

`vendor\phpxmlrpc\phpxmlrpc\src\Value.php`

**Comment by gggeek** [comment]
@sougatabose07 which version of the library are you using? Version 4.2.1 or 4.3 should have fixed the problem

**Comment by sougatabose07** [comment]
@gggeek its the master branch I installed (4.3.1).

I have changed it to older version 3.1.1 and implementing only the lib/ files for now.

**Comment by strausmann** [comment]
@gggeek  this is the Problem, can you fix that quickly?

lib/xmlrpc.inc:3183

```php/**
* Return next member element for xmlrpcvals of type struct.
* @return xmlrpcval
* @access public
*/
function structeach()
{
	return each($this->me['struct']);
}```

Thanks

**Comment by glensc** [comment]
@strausmann create new issue. don't comment on already solved tickets!

**Comment by gggeek** [comment]
@ strausmann I can fix that by silencing the warning, and release version 3.1.2.

Having said that, I _strongly_ encourage any users to move to version 4 of the library, which is fully api-compatible and comes with many improvements.

**Comment by strausmann** [comment]
@gggeek Thank you. A better HowTo to use the v4 are very good. Incl. the Encoder Class ;-)
