### ISSUE TITLE
Fault. Code: 5, Reason: Didn't receive 200 OK from remote server. (HTTP/1.1 401 Unauthorized) 1

### ISSUE THREAD

**Issue by bunalng** [gggeek/phpxmlrpc#58]
i was using old xmlrpc. but it is not support for php7. so i changed to this phpxmlrpc. but i have some trouble. my code is not working properly. i got this message:

`Fault. Code: 5, Reason: Didn't receive 200 OK from remote server. (HTTP/1.1 401 Unauthorized)`

but i have data also. but i cant access because of fault code 5.
this is debug output:
```
---SENDING---
<?xml version="1.0"?>
<methodCall>
<methodName>listAccounts</methodName>
<params>
<param>
<value><struct>
</struct></value>
</param>
</params>
</methodCall>
---END---
---CURL INFO---
url: https://server:443/xmlapi
content_type: text/xml
http_code: 200
header_size: 666
request_size: 887
filetime: -1
ssl_verify_result: 0
redirect_count: 1
total_time: 0.465894
namelookup_time: 4.7E-5
connect_time: 4.9E-5
pretransfer_time: 0.000203
size_upload: 156
size_download: 2042
speed_download: 4382
speed_upload: 334
download_content_length: -1
upload_content_length: 156
starttransfer_time: 0.19248
redirect_time: 0.268702
redirect_url: 
primary_ip: server
certinfo: 
primary_port: 443
local_ip: 10.10.10.10
local_port: 49952
---END---
---GOT---
HTTP/1.1 401 Unauthorized
Date: Thu, 26 Oct 2017 07:46:57 GMT
Server: Apache/2.2.22 (FreeBSD) mod_wsgi/2.8 Python/2.7.2 mod_ssl/2.2.22 OpenSSL/0.9.8q DAV/2
WWW-Authenticate: Digest nonce="759641ec5958f7e6d9752d62e2559b59", opaque="a27d06b15swc043df185ccb95173bbb9", realm="XML API", qop="auth"
Vary: Accept-Encoding
Content-Encoding: gzip
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8

HTTP/1.1 200 OK
Date: Thu, 26 Oct 2017 07:46:57 GMT
Server: Apache/2.2.22 (FreeBSD) mod_wsgi/2.8 Python/2.7.2 mod_ssl/2.2.22 OpenSSL/0.9.8q DAV/2
Vary: Accept-Encoding
Content-Encoding: gzip
Transfer-Encoding: chunked
Content-Type: text/xml

<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><struct>
<member>
<name>accounts</name>
<value><array><data>
<value><struct>
<member>
<name>username</name>
...
<value><string>OK</string></value>
</member>
</struct></value>
</param>
</params>
</methodResponse>

---END---
Fault. Code: 5, Reason: Didn't receive 200 OK from remote server. (HTTP/1.1 401 Unauthorized)
```

can you help me?

**Comment by bunalng** [comment]
i think problem is:
[php curl with digest returns two responses](https://stackoverflow.com/questions/13026725/php-curl-with-digest-returns-two-responses)

**Comment by bunalng** [comment]
i trace the error:
file: Helper/Html.php
line: 113
code:
`        if (!preg_match('/^HTTP\/[0-9.]+ 200 /', $data)) {
`
if i change this code to
`        if (!preg_match('/^HTTP\/[0-9.]+ 200 /m', $data)) {
`
it pass but there is another problem occur:
`XML error at line 1, check URLFault. Code: 2, Reason: Invalid return payload: enable debugging to examine incoming payload (XML error at line 1, check URL)`

**Comment by gggeek** [comment]
Hello.
Indeed the debug output you provided seems to point to the direction of cURL playing a nasty trick to php, i.e. returning the http headers for the 401 response before the http headers for the 200 response, all mashed together.

Your workaround at this point is partial: as it is it will probably try to parse as xml the 2nd set of http headers, and of course fail. To make it work correctly you should change the whole bit of code that parses the received http response to ignore a 1st set of http response headers (only for the 401 case?) and look for a second set of http headers to start parsing from.

To be honest, I am a bit loath to add such code to the library, as it seems a very specific corner case. And the code in the parseResponseHeaders method is already ugly enough. Also, the fact that it is reported only for the first time after so many years, makes me think that it must not be happening frequently.

The Stackoverflow article that you found out mentions as a way to work around this the recompilation of php with a newer curl library. Would it be possible in your case? Also, which exact versions of OS, PHP and curl are you using ?

**Comment by bunalng** [comment]
I met xmlrpc about 3 years ago. then phpXmlrpc gave the same error. the server administrator shared his own xmlrpc with me. the problem was solved. but this xmlrpc is very old and not compatible with php7. now I need to run the client on a php7 installed server. As a result I need to resolve this error in phpXmlrpc. If you can help in this matter, rejoice.

also the old xmlrpc work perfect in php5.6 still.

used versions;
os: debian stable 9.2
php: 7.0.19
curl: 7.52.1
xmlrpc: 1.3 (not working in php7)
phpxmlrpc: 4.2.2 (broken)
(only debian repository used)

**Comment by gggeek** [comment]
I will try to see if I can reproduce the problem using the stock versions of php and curl that come with debian 9, and keep you updated...

**Comment by bunalng** [comment]
i am waiting...

**Comment by gggeek** [comment]
Fixed in release 4.3.0

**Comment by bunalng** [comment]
hello again,
thanks for your effort and co operation.
but i have this error now:
`Fault. Code: 2, Reason: Invalid return payload: enable debugging to examine incoming payload found not-xmlrpc xml element NIL`
what do you think about this?

**Comment by bunalng** [comment]
i changed $xmlrpc_null_extension to true and it worked (file:PhpXmlRpc.php line:90). but is there any other way to change this var without edit PhpXmlRpc.php?

**Comment by bunalng** [comment]
found: PhpXmlRpc\PhpXmlRpc::$xmlrpc_null_extension = true;

thank you very much.

**Comment by bunalng** [comment]
error produces only while running on console:
`php script.php`
when i run with elinks there is no error:
`elinks https://localhost/script.php`

**Comment by gggeek** [comment]
I think the last comment should have been added to issue https://github.com/gggeek/phpxmlrpc/issues/59 ?
