### ISSUE TITLE
How do I create a 3 dimensional array?

### ISSUE THREAD

**Issue by Leesanwei** [gggeek/phpxmlrpc#64]
Hello,
I would like to create a 3 dimensional array to send to the webservice of a website. After a number of tries, I'm still can't get it to work. Here is my code : 

`$getId[] = new Value(array(new Value('name'),new Value('='),new Value($data['name'])),'struct');`

`$testId[] = new Value($getId, 'struct');`

`$id = $models->send(new Request('execute_kw',array(new Value($db), new Value($uid,'int'), new Value($password), new Value($resource), new Value ('search'), new Value($testId,'array'))));`

Where did I go wrong?
Thanks!

**Comment by gggeek** [comment]
Hello

I am not sure to 100% get what is your desired data structure. Could you describe it in another format?
At first sight you are missing the php array key for `$getId`, but it could be anything else as well...

One tip: as long sa there is no base64 encoding required, the easiest way to convert nested data structures between PHP and Value is to use the `PhpXmlRpc\Encoder` class. See fe: https://github.com/gggeek/phpxmlrpc/blob/master/demo/client/getstatename.php#L16

**Comment by Leesanwei** [comment]
This is a format I would like to use in PhpXmlRpc

`$id = $models->execute_kw($db, $uid, $password,
    'res.partner', 'search', array(
        array(array('name', '=', $name))));`

As you can see it's a 3 dimensional array.
Alright I will take a look at the Encoder class. Thanks :)

**Comment by gggeek** [comment]
Ok, so if it's 'just' an array of ararys (no named elements, only positional ones), no need to use `struct` in your calls to the constructor of Value, you should use `array`

**Comment by Leesanwei** [comment]
Got it, thanks!
