### ISSUE TITLE
Potential issue with serializedata()?

### ISSUE THREAD

**Issue by kyledyson** [gggeek/phpxmlrpc#65]
I'm not 100% if this is intended or I am causing the problem but I have had to edit source code to get it working. 

To reproduce call `addParam` on array: 

` $data['mac_list'] = [mac1, mac2]; `
`$macs = new \PhpXmlRpc\Value($data['mac_list'], "array");`
`$request->addParam($macs); `

Expected output: 
```
<params>
  <param> 
    <value> 
       <array>
          <data> 
              <value> 
                   <string> mac1 </string>
              <value> 
              <value> 
                   <string> mac1 </string>
              <value> 
         </data>
      </array>
   </value>
 </param>
</params>
```

Actual output: 
```
<b>Fatal error</b>:  Uncaught Error: Call to a member function serialize() on string in /srv/http/rps/vendor/phpxmlrpc/phpxmlrpc/src/Value.php:291
Stack trace:
#0 /srv/http/rps/vendor/phpxmlrpc/phpxmlrpc/src/Value.php(317): PhpXmlRpc\Value-&gt;serializedata('array', Array, '')
#1 /srv/http/rps/vendor/phpxmlrpc/phpxmlrpc/src/Request.php(59): PhpXmlRpc\Value-&gt;serialize('')
#2 /srv/http/rps/vendor/phpxmlrpc/phpxmlrpc/src/Request.php(91): PhpXmlRpc\Request-&gt;createPayload('')
#3 /srv/http/rps/scripts/rps.php(55): PhpXmlRpc\Request-&gt;serialize()
#4 /srv/http/rps/scripts/rps.php(32): xmlClient-&gt;encodeArray(Array, Object(PhpXmlRpc\Request))
#5 /srv/http/rps/scripts/rps.php(75): xmlClient-&gt;sendRequest(Array)
#6 /srv/http/rps/web/index.php(2): include('/srv/http/rps/s...')
#7 {main}
  thrown in <b>/srv/http/rps/vendor/phpxmlrpc/phpxmlrpc/src/Value.php</b> on line <b>291</b><br />
```

To fix I added: 
`$element = new \PhpXmlRpc\Value($element, "string");`

To `case 2` of `serializedata()' function: 

```
 case 2:
       // array
       $rs .= "<array>\n<data>\n";
       foreach ($val as $element) {
            $element = new \PhpXmlRpc\Value($element, "string");
            $rs .= $element->serialize($charsetEncoding);
       }
       $rs .= "</data>\n</array>";
       break;
```

**Comment by gggeek** [comment]
Hello
the fact is, you should have 'mac1' and 'mac2' be converted to a Value obj before being added to the php array.

Since doing manual wrapping of php values into Value objs is tedious for nested structures, you are encouraged to use the `PhpXmlRpc\Encoder` class for automated conversion. See fe: https://github.com/gggeek/phpxmlrpc/blob/master/demo/client/getstatename.php#L16 and https://github.com/gggeek/phpxmlrpc/blob/master/demo/client/which.php

**Comment by kyledyson** [comment]
Thanks for such a quick response. Ah my bad. Working as expected now.  
ps: Good job I was only using strings ;)
