### ISSUE TITLE
How to remove these unnecessary keys? “me”，“mytype”，“_php_class”

### ISSUE THREAD

**Issue by jzb1006** [gggeek/phpxmlrpc#74]
![image](https://user-images.githubusercontent.com/18511378/72604664-5688d480-3956-11ea-8841-5fa26c7618fe.png)

**Comment by gggeek** [comment]
Hello
I am afraid you might be mis-using or misunderstanding the library.
Why do you think there are 'unnecessary keys' in the base xmlrpcval objects? How are you using them?

**Comment by jzb1006** [comment]
So what method should I use to quickly get the "title" and "description" and other data in it?

**Comment by gggeek** [comment]
You can find examples of API usage within the library itself, as well as online.

Method 1: you can call `Encoder::decode()` on the value that you get back from `send` method. That will transform recursively the Response object and any Value object into native php values.
This is most convenient but not necessarily the fastest in terms of execution time. It also looses some of the type information that is carried by the xmlrpc Values (eg. you will not be able to tell apart a value transmitted as string from one transmitted as base64).

Sample code: https://github.com/gggeek/phpxmlrpc/blob/master/demo/client/which.php

Method 2: once you have a Value object, you can call the methods `scalarval`, `structmem`, `arraymem` to access the data. Note that while `scalarval` will give you back a php value, `structmem`, and `arraymem` will give you back a PhpXmlRpc\Value, so it is up to you to do recursive decoding.

Method 3: for 'struct' and 'array' values, you can access them as if they were php arrays. In this case, you will get back again PhpXmlRpc\Values.

Sample code: https://github.com/gggeek/phpxmlrpc/blob/master/demo/client/agesort.php

**Comment by jzb1006** [comment]
Thank you very much

**Comment by gggeek** [comment]
Ok, closing the issue then. Feel free to ask again if you have any further questions
