### ISSUE TITLE
curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead 

### ISSUE THREAD

**Issue by marcrichard2013** [gggeek/phpxmlrpc#76]
Hi,

I have this error, and the trace is :

File /src/vendor/phpxmlrpc/phpxmlrpc/src/Client.php line 1010
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, $this->verifyhost);
File /src/vendor/phpxmlrpc/phpxmlrpc/src/Client.php line 1010 in curl_setopt args
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, $this->verifyhost);
File /src/vendor/phpxmlrpc/phpxmlrpc/src/Client.php line 517 in PhpXmlRpc\Client::sendPayloadCURL args
$this->sslversion

I use PHP 7.4.6 and this last phpxmlrpc  version 

Best regards

**Comment by gggeek** [comment]
Hello. Did you change the value for the client's `$this->verifyhost` ?

**Comment by marcrichard2013** [comment]
hi, thanks I will change setSSLVerifyHost(1) by setSSLVerifyHost(2)

**Comment by gggeek** [comment]
All good it seems - closing. Feel free to open a new issue if you still have problems.
