### ISSUE TITLE
Issue sending request with struct

### ISSUE THREAD

**Issue by AlexHaaniWink** [gggeek/phpxmlrpc#79]
I'm using version 4.5.1.

I am trying to send an associative array as struct.
The request seems to serialize this array wrong. But when I serialize the created struct value it does serialize as expected. Am I doing something wrong here?

```php
$data = [
	'first' => 'foo',
	'second' => 'bar',
];

$encoder = new Encoder();
$params = $encoder->encode($data);

$request = new Request('method', $params);

echo $params->serialize();
echo $request->serialize();
```
This gives (reformatted for readability):

```xml
<value>
	<struct>
		<member>
			<name>first</name>
			<value>
				<string>foo</string>
			</value>
		</member>
		<member>
			<name>second</name>
			<value>
				<string>bar</string>
			</value>
		</member>
	</struct>
</value>
```

and

```xml
<?xml version="1.0"?>
<methodCall>
<methodName>method</methodName>
<params>
	<param>
		<value>
			<string>foo</string>
		</value>
	</param>
	<param>
		<value>
			<string>bar</string>
		</value>
	</param>
</params>
</methodCall>
```

Clearly the request serializes the struct differently.

I'm trying to replace used of Zend_XmlRpc_Client with this library by the way. I'm just trying to recreate the same request structure before I'm going to use this in communication with an external service.

**Comment by AlexHaaniWink** [comment]
OH. Sorry. Just after I posted this, after thinking about this for quite some time, I realize that perhaps I should pass the params to Request as array. And yes. There we go.

Closing this.

**Comment by gggeek** [comment]
Indeed, the fact of writing down things is known to help both in clarifying understanding and memorizing.
Happy that you found a solution.
ps: I think that the second arg to `Request::send` is clearly documented as having to be an array of Value... feel free to suggest if the documentation needs any improvements

**Comment by AlexHaaniWink** [comment]
Yes, the documentation is clear enough. Since passing along a struct parameter did sort of work too, it is an iterable after all, I started looking in the wrong place. And I guess I was just dead set on the flow I used before.

Thank you for maintaining this library!

**Comment by gggeek** [comment]
Lol. I did wonder, when making Value iterables, where/when it would come back to bite me. It seems it bit you instead :-D

**Comment by gggeek** [comment]
ps: I wonder if it might be worth adding a check in the Request, before iterating over `$params`, to check that it is not in fact a Value, as you did, and at least log a warning... Other iterables could be ok, but Value is surely unexpected there...

**Comment by AlexHaaniWink** [comment]
You could block it, or just cast a single `Value` to an array and accept both (and document as such).
In my situation both calls to the XMLRPC method used a struct as single parameter.

I now wonder whether passing a single Array `Value` would result in any difference to the XML structure compared to an array of `Values`. I can't look into that now though.

**Comment by gggeek** [comment]
Passing in a single Array value nesting the other values would work. But I would not recommend it at all, as it obfuscates the correct api usage and is just a lucky side effect of current code, which might become broken in the future at any time... (see https://xkcd.com/1172/ )

**Comment by AlexHaaniWink** [comment]
Heh yes, that's a nice XKCD.

I didn't mean that developers should wrap their parameter to the `Request` constructor themselves.

But instead at https://github.com/gggeek/phpxmlrpc/blob/master/src/Request.php#L78 
- check whether `$params` is a `Value`, if so, add just that single param (it's only 3 lines of code here, so where I said "cast a single `Value to an array" it is just as simple to add it straight away). Thus accepting both `Value[]` and `Value`.

But you could also ignore/error/exception on such a faulty parameter as you said.
