### ISSUE TITLE
Vulnerability detected CWE ID 88 Logger.php in version 4.2.0

### ISSUE THREAD

**Issue by TatianaGarcia94** [gggeek/phpxmlrpc#82]
En la ruta: /src/Helper/Logger.php 46
Nombre de la vulnerabilidad: Improper Neutralization of Argument Delimiters in a Command ('Argument Injection')
Modo de detección: Se realizó un escaneo estático, el cuál detecto la línea mencionada como vulnerabilidad según los estándares de seguridad

**Comment by gggeek** [comment]
I am not sure if this should be considered a vulnerability.

The line in question is:
`print "\n$message\n";` 

It is part of a method meant to echo debugging information.
It is only executed when php is using the CLI sapi, ie. in console mode.

As such, I do not consider that it is the duty of the application to carry out any particular escaping of the output, even if it comes from untrusted sources.
Fe. a character sequence which will jumble a bash shell might be different from one devised to screw up an xterm or a windows console. The php application using this library can not have knowledge of which kind of terminal is used to view its textual output, or if that is being saved to a file. In which case, 'attack character sequences' will be even different, as they might target a specific text-file editor or viewer, or a complex software pipeline used to store, transmit and view the file
