### ISSUE TITLE
about feof() may get an infinite loop

### ISSUE THREAD

**Issue by mokeyjay** [gggeek/phpxmlrpc#85]
I had a problem with infinite loops in my local docker environment. After troubleshooting, it's a problem with the `feof()`
```php
$ipd = '';
do {
    // shall we check for $data === FALSE?
    // as per the manual, it signals an error
    $ipd .= fread($fp, 32768);
} while (!feof($fp));
fclose($fp);
```
> [src/Client.php#L831](https://github.com/gggeek/phpxmlrpc/blob/b337d292eb5b5656d27a2fc9ab6796be300c59a3/src/Client.php#L831)

The official documentation has said that there may be a problem with this function
![image](https://user-images.githubusercontent.com/6757507/129153010-df0b6bd4-dd9c-4930-9a86-6101a9f60d14.png)

I don't know why I encountered this problem. I finally solved the problem with the following code. Maybe you can refer to it
```php
$ipd = '';
$ipdLen = 0;
do {
    // shall we check for $data === FALSE?
    // as per the manual, it signals an error
    $ipdLen = strlen($ipd);
    $ipd .= fread($fp, 32768);

    if (strlen($ipd) === $ipdLen) {
        break;
    }
} while (!feof($fp));
fclose($fp);
```

**Comment by gggeek** [comment]
Hello.

This is weird, as the code does check a few lines above that $fp is a valid file pointer, by way of checking that `stream_socket_client()` returned a non null value, and then pushing data to it via `fputs`.
Also, this lib has been in use for a long time, and I don't remember having changed those lines recently - meaning that what happened to you is definitely not common.

Having said that, there might indeed be some very narrow timing condition or other exceptional condition which would make the file pointer "invalid" halfway through the loop while still making feof return false (even though the doc also states that "Returns true if the file pointer is at EOF _or an error occurs (including socket timeout)_;") - I am not even sure what "invalid" exactly means in this context.

Do you have a way to reproduce the infinite-loop error?

**Comment by mokeyjay** [comment]
Sorry, I can't reproduce this issue outside of my local Docker environment, maybe it's just a problem with my Docker network
