### ISSUE TITLE
Invalid response payload - found not-xmlrpc xml element NIL

### ISSUE THREAD

**Issue by helloadmin** [gggeek/phpxmlrpc#91]
I'm getting an error thrown that the XMLRPC is not well formed because it has a NIL element in it

Here is a snippet of the `<methodResponse>`
```
<member>
<name>registration_status</name>
<value><nil/></value></member>
```

I've reviewed the xml multiple times to ensure it is valid according to xml standards and xmlrpc parents and it appears to be.

On line 77 of phpxmlrpc/src/Helper/XMLParser.php   there is a comment:

'NIL' => array('VALUE'), // only used when extension activated

I'm wondering if this may be related.  What extension is the comment referring to and how do I ensure it is "activated"?

**Comment by gggeek** [comment]
It is an "extension" of the spec, really. This lib does not have a concept of extensions /plugins - but there are knobs which can be used to tweak the parsing - as well as the emitted xml.

What you are looking for is to add somewhere in your code, before any xmlrpc payload is received or generated, `PhpXmlRpc\PhpXmlRpc::$xmlrpc_null_extension = true`.

**Comment by helloadmin** [comment]
Thank you!
