### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by kierandelaney** [gggeek/phpxmlrpc#92]
Working through list of issues, I could probably raise a PR for the fixes I find, time is limited so will almost certainly add to this list

- Fatal error: Uncaught Error: Call to undefined function PhpXmlRpc\Helper\each() in ..../vendor/phpxmlrpc/phpxmlrpc/src/Helper/Http.php on line 136 - each was dep'd in 7.2, removed in 8.0
	- Replaced line with `foreach ($ar as $line){`

**Comment by gggeek** [comment]
Hello.
Are you sure you are not using an old version of the library? On line 136 of /src/Helper/Http.php, there is currently `$pos = strpos($data, "\r\n\r\n");`, and the only occorrence of `each` still in the code is in method `Value::structeach`, which is deprecated

**Comment by kierandelaney** [comment]
Ah, so the issue is - the install instructions may need a tweak. 

- `composer require phpxmlrpc/phpxmlrpc:4` specifically installs version 4.
- `composer require phpxmlrpc/phpxmlrpc:^4` is posibly a better command for your INSTALL.md document

:)

**Comment by gggeek** [comment]
Thx. Fixed in master's INSTALL instructions.

**Comment by kierandelaney** [comment]
Thanks a lot for the support, happy holidays :)
