### ISSUE TITLE
PHP 8 undefined array key.

### ISSUE THREAD

**Issue by rotdrop** [gggeek/phpxmlrpc#97]
https://github.com/gggeek/phpxmlrpc/blob/4aa50ce5fa97d7c5af7605ac5ec65e47827f53f8/src/Helper/Http.php#L186

Could we replace this by `$val = trim($val[1] ?? ''); `?

**Comment by gggeek** [comment]
Not exactly, as min php version supported is 5.3. But we can use `isset`

**Comment by gggeek** [comment]
Fixed in 4.6.1
