### ISSUE TITLE
Class "PhpXmlRpc\Exception\PhpXmlrpcException" not found

### ISSUE THREAD

**Issue by rolandseuhs** [gggeek/phpxmlrpc#99]
I have used Version 4.4.1 successfully for years, after upgrading to 4.7.2 I get this error when including lib/xmlrpc.inc:

Class "PhpXmlRpc\Exception\PhpXmlrpcException" not found

The error appears on both PHP 7 and 8.1.

**Comment by rolandseuhs** [comment]
The error also appears on Version 4.6.0

Which version is the first version that is compatible with PHP 8.1 ?

**Comment by rolandseuhs** [comment]
I think I have found it:

in lib/xmlrpc.inc, the order of includes needs to be changed:

causes error:

include_once(__DIR__.'/../src/Exception/HttpException.php');
include_once(__DIR__.'/../src/Exception/PhpXmlrpcException.php');

no error:

include_once(__DIR__.'/../src/Exception/PhpXmlrpcException.php');
include_once(__DIR__.'/../src/Exception/HttpException.php');

**Comment by gggeek** [comment]
Thanks for the report. I ll try to get a new release with a fix out within a week or so. Btw, which php version are you running on, 8.1 ?

**Comment by rolandseuhs** [comment]
Yes, we run 8.1.7, the new PHP-version is the reason for the upgrade phpxmlrpc

**Comment by gggeek** [comment]
Should be fixed in 4.8.0.

Btw, I warmly recommend to start planning to refactor the app you are using to use the new API of the phpxmlrpc lib rather than relying on file xmlrpc.inc
